# .github/dependabot.yml
version: 2
updates:
  # This section is for updating dependencies in the GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional: Add ignore rule to skip specific versions or packages
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["2.x"]

  # This section is for updating dependencies in your JavaScript (Node.js) project
  - package-ecosystem: "npm"
    directory: "/" # Location of the package.json or yarn.lock file
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react"
        versions: ["17.x"]

  # This section is for updating dependencies in your Python project
  - package-ecosystem: "pip"
    directory: "/" # Location of the requirements.txt or Pipfile.lock file
    schedule:
      interval: "weekly"

  # This section is for updating dependencies in your Dockerfile
  - package-ecosystem: "docker"
    directory: "/" # Location of the Dockerfile
    schedule:
      interval: "daily"

  # This section is for updating dependencies in your Terraform files
  - package-ecosystem: "terraform"
    directory: "/" # Location of the Terraform files
    schedule:
      interval: "monthly"
    # Optional: Add open-pull-requests-limit to limit the number of open PRs
    open-pull-requests-limit: 5

  # This section is for updating dependencies in your Gradle project
  - package-ecosystem: "gradle"
    directory: "/" # Location of the build.gradle or build.gradle.kts file
    schedule:
      interval: "weekly"

  # This section is for updating dependencies in your Swift project
  - package-ecosystem: "swift"
    directory: "/" # Location of the Package.swift file
    schedule:
      interval: "weekly"

  # You can add more sections for different ecosystems as needed
