# .github/dependabot.yml
version: 2
updates:
  # This section is for updating dependencies in the GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional: Add ignore rule to skip specific versions or packages
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["2.x"]

 
